spring:
  application:
    name: rocketmq-provider
  cloud:
    stream:
      bindings:
        output:
          destination:  joker
          contentType: application/json
          group: myself-group
      rocketmq:
        binder:
          name-server: 192.168.188.130:9876

server:
  port: 8200
rocketmq:
  name-server: 192.168.188.130:9876
  producer:
    group: myself-group